### ISSUE TITLE
parse.js is missing

### ISSUE THREAD

**Issue by jaeh** [ksm2/svg-parse#1]
just installed this package to take a look at it,

index.js fails in importing parse.js

**Comment by ksm2** [comment]
Hi @jaeh, thanks for reporting the issue! I will add a `prepack` script to solve the issue.
I also checked the published package at NPM, which is fine. I won't re-release the package therefore.

**Comment by jaeh** [comment]
oh thats nice, i thought i triggered the issue in the npm installed package as well,
seems i got that mixed up by installing from this github but using npm.
